### ISSUE TITLE
start tag excpected

### ISSUE THREAD

**Issue by RasmusEk** [ckoval7/df-aggregator#12]
Trying to connect df-aggregator to krakens output html which for me is "http://192.168.88.250:8081/DOA_value.html" yields following error

![Screenshot from 2024-04-11 14-30-21](https://github.com/ckoval7/df-aggregator/assets/90400312/35e0bbaa-fd96-4ab1-8fbe-f5337c4b5de6)

kraken seems to be configured correctly 

![Screenshot from 2024-04-11 14-31-00](https://github.com/ckoval7/df-aggregator/assets/90400312/feacdbbc-f267-4d10-9740-a7881fa581e2)

![Screenshot from 2024-04-11 14-31-43](https://github.com/ckoval7/df-aggregator/assets/90400312/053b43c9-badf-4ef2-ae56-955f1fa8b932)

the html output from kraken also seems to be working correctly

![Screenshot from 2024-04-11 14-51-48](https://github.com/ckoval7/df-aggregator/assets/90400312/1fa0d97f-8d99-4f58-8f28-bebcb0f9cc70)

My thought is that there is a problem with df-aggregator reading the html page, I am trying to trubleshoot the issue have anyone experienced something similar. I have read the previous fixed issue where the user was outputting kraken app data to the html page

**Comment by RasmusEk** [comment]
I really need this to work so trying to debug the issue I found that I get the same error if I run etree as a stand alone in a test function. The script as seen bellow:

from icecream import ic
import pandas as pd
from lxml import etree
data = pd.read_csv('http://192.168.88.250:8081/DOA_value.html')
ic(data)
xml_contents = etree.parse('http://192.168.88.250:8081/DOA_value.html')

Gives me following readout

ic| data: Empty DataFrame
          Columns: [1709292568894,  270.0,  0.38096465170383453,  -51.80131912231445,  100000000,  ULA,  436,  OCALL,  420.420420420420,  -69.69696969696,  0,  0.1,  GPS,  R,  R.1,  R.2,  R.3,  0.03,  0.03.1,  0.03.2,  0.02,  0.02.1,  0.02.2,  0.02.3,  0.01,  0.01.1,  0.01.2,  0.01.3,  0.01.4,  0.01.5,  0.00,  0.00.1,  0.00.2,  0.00.3,  0.00.4,  0.00.5,  0.00.6,  0.00.7,  0.00.8,  0.00.9,  0.00.10,  0.00.11,  0.00.12,  0.00.13,  0.00.14,  0.00.15,  0.00.16,  0.00.17,  0.01.6,  0.01.7,  0.01.8,  0.01.9,  0.01.10,  0.01.11,  0.01.12,  0.01.13,  0.02.4,  0.02.5,  0.02.6,  0.02.7,  0.02.8,  0.02.9,  0.03.3,  0.03.4,  0.03.5,  0.03.6,  0.03.7,  0.03.8,  0.04,  0.04.1,  0.04.2,  0.04.3,  0.04.4,  0.05,  0.05.1,  0.05.2,  0.05.3,  0.05.4,  0.05.5,  0.06,  0.06.1,  0.06.2,  0.06.3,  0.06.4,  0.06.5,  0.06.6,  0.07,  0.07.1,  0.07.2,  0.07.3,  0.07.4,  0.07.5,  0.07.6,  0.07.7,  0.07.8,  0.08,  0.08.1,  0.08.2,  0.08.3,  0.08.4, ...]
          Index: []
          
          [0 rows x 377 columns]
Traceback (most recent call last):
  File "/home/rasmusek/workspace/testCSVparser/theParser.py", line 15, in <module>
    xml_contents = etree.parse('http://192.168.88.250:8081/DOA_value.html')
  File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "http://192.168.88.250:8081/DOA_value.html", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

Can someone that knows csv parsing help me determine why etree gives me this error

**Comment by alphafox02** [comment]
I would suggest pulling an older version of the Kraken software. I recall, seeing in the change logs that there was some work done to the various outputs. Perhaps that broke things in your case. I’ve not updated to the latest Kraken software, I probably should though, and check it.

**Comment by alphafox02** [comment]
It’s also possible maybe you’re on this commit 

https://github.com/krakenrf/krakensdr_doa/commit/ca9ab97a1bf4160162f9bf1f641a59b4553df541

Which in a later commit seems like a bug was corrected.

**Comment by RasmusEk** [comment]
The marsh 3 build wouldn't affect me, but I will revert to an earlier build tomorrow

**Comment by alphafox02** [comment]
I notice you are using the html URL as I’ve always used to, but it was mentioned to me that in a recent change the output changed to XML and requires telling DFA to use that url vs what we’ve been using. 

In a recent commit this is mentioned “ Save XML unconditionally, e.g., used by DF-Aggregator” but I’m not sure what the new URL is until I can get to my setup.

**Comment by RasmusEk** [comment]
reverted to an earlier build and that seems to have fixed the bulk of the problem

**Comment by alphafox02** [comment]
https://github.com/krakenrf/krakensdr_doa/issues/138#issuecomment-2080405623
