### ISSUE TITLE
U can add central lot lan ?

### ISSUE THREAD

**Issue by jhonnybonny** [ckoval7/df-aggregator#5]
Hello , do you can add central lat lon ? 

like this (for example) : 

![](https://raw.githubusercontent.com/jhonnybonny/just-pic-/main/vMxd6FbC.png-small.png)

**Comment by jhonnybonny** [comment]
And it would also be nice to make an full offline version and use the OpenStreetMap local server

**Comment by ckoval7** [comment]
The lat/lon of a point is available by clicking on it. See the attached screenshot.

![127 0 0 1:8080 - Google Chrome_045](https://user-images.githubusercontent.com/7625615/198418441-a58fd776-cf50-4fdd-9e2e-20714310927a.png)


As for setting up an offline OpenStreetMap server, that is beyond the scope of this repo. Hosting a tile server is a skill-set all on it's own. Here are some helpful resources:
[A blog on using offline OSM with Cesium](https://mrgood.blog/posts/2021-12-28-cesium-tile/post.html)
[Cesium Docs pertaining to offline imagery](https://cesium.com/learn/cesiumjs/ref-doc/UrlTemplateImageryProvider.html)
[DFA Wiki](https://github.com/ckoval7/df-aggregator/wiki/OfflineGuide)
